import type { LucideIcon } from 'lucide-react'
import {
  AlertTriangle,
  Award,
  Banknote,
  BarChart3,
  Bell,
  Bot,
  Briefcase,
  Building2,
  Cable,
  Calculator,
  CalendarDays,
  CheckCircle2,
  ClipboardList,
  Clock,
  Cloud,
  Database,
  Download,
  Eye,
  FileSignature,
  FileText,
  Filter,
  FolderOpen,
  Gavel,
  GitBranch,
  GraduationCap,
  HardHat,
  HeartPulse,
  History,
  Key,
  Languages,
  Layers,
  LayoutGrid,
  Link2,
  ListChecks,
  Lock,
  MapPin,
  MessageSquare,
  Percent,
  PieChart,
  Plug,
  Receipt,
  RefreshCw,
  Scale,
  ScanFace,
  Search,
  Send,
  Server,
  ShieldCheck,
  Smartphone,
  Sparkles,
  Stethoscope,
  Table,
  Target,
  TrendingUp,
  Upload,
  UserCheck,
  UserPlus,
  Users,
  Wallet,
  Workflow,
  Zap,
} from 'lucide-react'

/** Ícones permitidos no conteúdo dos módulos (traço 1,6 px, estilo outline — manual, seção 10). */
export const moduleIcons = {
  'alert-triangle': AlertTriangle,
  award: Award,
  banknote: Banknote,
  'bar-chart': BarChart3,
  bell: Bell,
  bot: Bot,
  briefcase: Briefcase,
  building: Building2,
  cable: Cable,
  calculator: Calculator,
  calendar: CalendarDays,
  'check-circle': CheckCircle2,
  clipboard: ClipboardList,
  clock: Clock,
  cloud: Cloud,
  database: Database,
  download: Download,
  eye: Eye,
  'file-signature': FileSignature,
  'file-text': FileText,
  filter: Filter,
  folder: FolderOpen,
  gavel: Gavel,
  'git-branch': GitBranch,
  'graduation-cap': GraduationCap,
  'hard-hat': HardHat,
  'heart-pulse': HeartPulse,
  history: History,
  key: Key,
  languages: Languages,
  layers: Layers,
  'layout-grid': LayoutGrid,
  link: Link2,
  'list-checks': ListChecks,
  lock: Lock,
  'map-pin': MapPin,
  'message-square': MessageSquare,
  percent: Percent,
  'pie-chart': PieChart,
  plug: Plug,
  receipt: Receipt,
  refresh: RefreshCw,
  scale: Scale,
  'scan-face': ScanFace,
  search: Search,
  send: Send,
  server: Server,
  'shield-check': ShieldCheck,
  smartphone: Smartphone,
  sparkles: Sparkles,
  stethoscope: Stethoscope,
  table: Table,
  target: Target,
  'trending-up': TrendingUp,
  upload: Upload,
  'user-check': UserCheck,
  'user-plus': UserPlus,
  users: Users,
  wallet: Wallet,
  workflow: Workflow,
  zap: Zap,
} satisfies Record<string, LucideIcon>

export type IconName = keyof typeof moduleIcons
