/* +========================================================================================+
   |  ONTOLOGIA DE RECRUTAMENTO - 01  TABELAS                                                 |
   +========================================================================================+
   Cria as tabelas ONT_* (nenhuma tabela existente e alterada). Rodar no MESMO esquema das
   tabelas de RH (REQUISICAO, INF_PESSOAIS_CANDIDATO...), depois do 00_conferir.sql sem FALTA.
   Guia: LEIA-ME.md.

   Grupos:
     [T1] Ajustes        ONT_CONFIG, ONT_PESO, ONT_CRITERIO_ORIGEM
     [T2] Vocabulario    ONT_PALAVRA_FRACA, ONT_ABREVIACAO
     [T3] Ontologia      ONT_CONCEITO, ONT_TERMO, ONT_TERMO_TOKEN, ONT_RELACAO, ONT_CONCEITO_FECHO
     [T4] Escalas        ONT_INSTRUCAO_ORDEM, ONT_NIVEL_ORDEM
     [T5] Geografia      ONT_MUNICIPIO_GEO, ONT_GEO_CEP
     [T6] Candidato      ONT_CAND_CONTROLE, ONT_CAND_LINHA, ONT_CAND_LINHA_TOKEN, ONT_CAND_CONCEITO
     [T7] Requisicao     ONT_REQ_ITEM
     [T8] Curadoria      ONT_PENDENTE
     [T9] Resultado      ONT_ADERENCIA, ONT_ADERENCIA_ITEM, ONT_LOG
*/
set define off
alter session set nls_length_semantics = char;

/* === [T1] AJUSTES ======================================================================= */
create table ont_config (
  chave      varchar2(40)  constraint ont_config_pk primary key,
  valor      varchar2(400),
  descricao  varchar2(500)
);

create table ont_peso (
  criterio        varchar2(20)  constraint ont_peso_pk primary key,
  peso_exigido    number(5,2)   not null,
  peso_desejavel  number(5,2)   not null,
  ativo           varchar2(1)   default 'S' not null constraint ont_peso_ativo_ck check (ativo in ('S','N')),
  descricao       varchar2(500)
);

/* em quais linhas do cadastro do candidato cada criterio procura (PODE MEXER) */
create table ont_criterio_origem (
  criterio  varchar2(20) not null,
  origem    varchar2(20) not null,
  constraint ont_criterio_origem_pk primary key (criterio, origem)
);

/* === [T2] VOCABULARIO =================================================================== */
create table ont_palavra_fraca (
  palavra  varchar2(40) constraint ont_palavra_fraca_pk primary key
);

/* abreviacao que NAO e comeco da palavra ("an" = analista). As que sao (adm, aux, eng) ja casam. */
create table ont_abreviacao (
  token     varchar2(20)  constraint ont_abreviacao_pk primary key,
  expansao  varchar2(60)  not null
);

/* === [T3] ONTOLOGIA ===================================================================== */
create table ont_conceito (
  id           number generated by default as identity constraint ont_conceito_pk primary key,
  tipo         varchar2(20)  not null
               constraint ont_conceito_tipo_ck check (tipo in ('FORMACAO','CURSO','CONHECIMENTO','OCUPACAO','AREA')),
  nome         varchar2(200) not null,
  cod_externo  varchar2(40),
  origem       varchar2(30)  default 'MANUAL' not null,
  ativo        varchar2(1)   default 'S' not null constraint ont_conceito_ativo_ck check (ativo in ('S','N')),
  criado_em    date          default sysdate not null,
  criado_por   varchar2(100) default user not null
);
create unique index ont_conceito_uk on ont_conceito (tipo, upper(nome));
create index ont_conceito_ext on ont_conceito (cod_externo);

create table ont_termo (
  id           number generated by default as identity constraint ont_termo_pk primary key,
  conceito_id  number        not null constraint ont_termo_conceito_fk references ont_conceito (id) on delete cascade,
  texto        varchar2(300) not null,
  texto_norm   varchar2(300) not null,
  tipo         varchar2(12)  default 'SINONIMO' not null
               constraint ont_termo_tipo_ck check (tipo in ('PREFERIDO','SINONIMO','SIGLA','ABREVIACAO','ERRO')),
  n_tokens     number(3)     not null,
  criado_em    date          default sysdate not null,
  criado_por   varchar2(100) default user not null
);
create unique index ont_termo_uk on ont_termo (conceito_id, texto_norm);
create index ont_termo_norm on ont_termo (texto_norm);

create table ont_termo_token (
  termo_id  number       not null constraint ont_termo_token_fk references ont_termo (id) on delete cascade,
  posicao   number(3)    not null,
  token     varchar2(60) not null,
  p3        varchar2(3)  not null,
  constraint ont_termo_token_pk primary key (termo_id, posicao)
);
create index ont_termo_token_p3 on ont_termo_token (p3, token);
create index ont_termo_token_tk on ont_termo_token (token);

/* AMPLO: conceito_id e um tipo de alvo_id ("MBA em Gestao de Pessoas" -> "Gestao de Pessoas").
   RELACIONADO: parecidos, valem "peso" (0 a 1) um pelo outro. */
create table ont_relacao (
  conceito_id  number      not null constraint ont_relacao_c_fk references ont_conceito (id) on delete cascade,
  tipo         varchar2(12) not null constraint ont_relacao_tipo_ck check (tipo in ('AMPLO','RELACIONADO')),
  alvo_id      number      not null constraint ont_relacao_a_fk references ont_conceito (id) on delete cascade,
  peso         number(3,2) default 0.3 not null constraint ont_relacao_peso_ck check (peso between 0 and 1),
  constraint ont_relacao_pk primary key (conceito_id, tipo, alvo_id),
  constraint ont_relacao_auto_ck check (conceito_id <> alvo_id)
);
create index ont_relacao_alvo on ont_relacao (alvo_id, tipo);

/* palavras COMPLETAS conhecidas (4+ letras, dos nomes e sinonimos). Uma palavra daqui nao vale como
   abreviacao: "excel" nao casa com "excelente", "java" nao casa com "javascript". */
create table ont_vocab (
  token  varchar2(60) constraint ont_vocab_pk primary key
);

/* fecho de AMPLO (todos os ancestrais de cada conceito) - refeito por ont_ontologia.recalcular_fecho */
create table ont_conceito_fecho (
  conceito_id   number    not null,
  ancestral_id  number    not null,
  distancia     number(2) not null,
  constraint ont_conceito_fecho_pk primary key (conceito_id, ancestral_id)
);
create index ont_conceito_fecho_anc on ont_conceito_fecho (ancestral_id);

/* === [T4] ESCALAS (niveis comparaveis) ==================================================
   Preenchidas no 07_carga.sql a partir de INSTRUCAO e NIVEL_CONHECIMENTO; conferir uma vez
   (coluna CONFERIDO) - a ordem e o que decide "igual ou maior". */
create table ont_instrucao_ordem (
  cod        varchar2(20)  constraint ont_instrucao_ordem_pk primary key,
  nome       varchar2(200),
  ordem      number(4,1),
  conferido  varchar2(1)   default 'N' not null
);

create table ont_nivel_ordem (
  codigo     varchar2(20)  constraint ont_nivel_ordem_pk primary key,
  descricao  varchar2(200),
  ordem      number(2),
  conferido  varchar2(1)   default 'N' not null
);

/* === [T5] GEOGRAFIA ===================================================================== */
/* sede de cada municipio (IBGE). cod_ibge6 = sem o digito verificador (padrao RAIS). */
create table ont_municipio_geo (
  cod_ibge7  number(7)     constraint ont_municipio_geo_pk primary key,
  cod_ibge6  number(6)     not null,
  nome       varchar2(100) not null,
  nome_norm  varchar2(100) not null,
  uf         varchar2(2)   not null,
  latitude   number(9,6)   not null,
  longitude  number(9,6)   not null,
  capital    varchar2(1)   default 'N' not null
);
create index ont_municipio_geo_6 on ont_municipio_geo (cod_ibge6);
create index ont_municipio_geo_nome on ont_municipio_geo (nome_norm, uf);

/* OPCIONAL - coordenada do proprio CEP (mais precisa que a do municipio). Fica vazia ate alguem
   carregar (geocodificacao). Quando houver, ela tem prioridade. */
create table ont_geo_cep (
  cep              number(5)   not null,
  complemento_cep  number(3)   not null,
  latitude         number(9,6) not null,
  longitude        number(9,6) not null,
  fonte            varchar2(60),
  constraint ont_geo_cep_pk primary key (cep, complemento_cep)
);

/* === [T6] CANDIDATO (o cadastro em linhas classificadas) ================================ */
create table ont_cand_controle (
  cod_candidato     number        constraint ont_cand_controle_pk primary key,
  classificado_em   date          not null,
  anos_experiencia  number(6,2),
  latitude          number(9,6),
  longitude         number(9,6),
  geo_precisao      varchar2(20),  -- CEP | MUNICIPIO_CEP | MUNICIPIO_NOME
  geo_descricao     varchar2(150)
);

create table ont_cand_linha (
  id             number generated by default as identity constraint ont_cand_linha_pk primary key,
  cod_candidato  number         not null,
  origem         varchar2(20)   not null,  -- FORMACAO, CURSO, HABILIDADE, EMPREGO, QUALIF, OBS_FORMACAO, OBS_CURSO, OBS_HABILIDADE
  texto          varchar2(1000) not null,  -- como aparece para o recrutador
  texto_norm     varchar2(1000) not null,  -- o que e comparado
  concluido      varchar2(1),
  nivel_ordem    number(2),
  data_ini       date,
  data_fim       date
);
create index ont_cand_linha_cand on ont_cand_linha (cod_candidato, origem);
create index ont_cand_linha_norm on ont_cand_linha (texto_norm);

create table ont_cand_linha_token (
  linha_id  number       not null constraint ont_cand_linha_token_fk references ont_cand_linha (id) on delete cascade,
  token     varchar2(60) not null,
  p3        varchar2(3)  not null,
  constraint ont_cand_linha_token_pk primary key (linha_id, token)
);
create index ont_cand_linha_token_p3 on ont_cand_linha_token (p3, token);

create table ont_cand_conceito (
  linha_id     number      not null constraint ont_cand_conceito_l_fk references ont_cand_linha (id) on delete cascade,
  conceito_id  number      not null constraint ont_cand_conceito_c_fk references ont_conceito (id) on delete cascade,
  termo_id     number,
  exato        varchar2(1) not null,   -- S: todas as palavras iguais; N: por comeco de palavra/1 letra
  constraint ont_cand_conceito_pk primary key (linha_id, conceito_id)
);
create index ont_cand_conceito_c on ont_cand_conceito (conceito_id);

/* === [T7] REQUISICAO (os requisitos em itens comparaveis) =============================== */
create table ont_req_item (
  cod_req      number         not null,
  seq          number(4)      not null,
  criterio     varchar2(20)   not null,
  texto        varchar2(1000),
  texto_norm   varchar2(1000),
  conceito_id  number         constraint ont_req_item_c_fk references ont_conceito (id) on delete set null,
  exige        varchar2(1)    not null constraint ont_req_item_exige_ck check (exige in ('S','N')),
  nivel_ordem  number(4,1),
  codigo       varchar2(40),   -- idioma, cargo, local de trabalho
  valor_num    number,         -- anos de experiencia, salario
  constraint ont_req_item_pk primary key (cod_req, seq)
);
create index ont_req_item_conceito on ont_req_item (conceito_id);

/* === [T8] CURADORIA ===================================================================== */
create table ont_pendente (
  id             number generated by default as identity constraint ont_pendente_pk primary key,
  texto_norm     varchar2(1000) not null,
  exemplo        varchar2(1000),
  origem         varchar2(20),
  ocorrencias    number         default 0 not null,
  sugestao_id    number         constraint ont_pendente_sug_fk references ont_conceito (id) on delete set null,
  status         varchar2(10)   default 'ABERTO' not null
                 constraint ont_pendente_status_ck check (status in ('ABERTO','RESOLVIDO','IGNORADO')),
  resolvido_por  varchar2(100),
  resolvido_em   date,
  primeira_vez   date           default sysdate not null,
  ultima_vez     date           default sysdate not null
);
create unique index ont_pendente_uk on ont_pendente (texto_norm);
create index ont_pendente_fila on ont_pendente (status, ocorrencias);

/* === [T9] RESULTADO ===================================================================== */
create table ont_aderencia (
  cod_req         number       not null,
  cod_candidato   number       not null,
  pct             number(5,1)  not null,
  pontos          number(9,3)  not null,
  maximo          number(9,3)  not null,
  exig_total      number(3)    not null,
  exig_ok         number(3)    not null,
  eliminado       varchar2(1)  default 'N' not null,
  motivo          varchar2(300),
  distancia_km    number(7,1),
  geo_precisao    varchar2(20),
  calculado_em    date         default sysdate not null,
  constraint ont_aderencia_pk primary key (cod_req, cod_candidato)
);
create index ont_aderencia_rank on ont_aderencia (cod_req, eliminado, pct desc);

create table ont_aderencia_item (
  cod_req        number         not null,
  cod_candidato  number         not null,
  seq            number(4)      not null,
  criterio       varchar2(20)   not null,
  requisito      varchar2(1000),
  exige          varchar2(1)    not null,
  peso           number(5,2)    not null,
  nota           number(4,3)    not null,
  valor          number(14,2),     -- o numero por tras da nota: km (DISTANCIA), anos (TEMPO), salario (SALARIO)
  evidencia      varchar2(1000),
  constraint ont_aderencia_item_pk primary key (cod_req, cod_candidato, seq)
);

create table ont_log (
  id        number generated by default as identity constraint ont_log_pk primary key,
  quando    date          default sysdate not null,
  rotina    varchar2(60)  not null,
  mensagem  varchar2(4000),
  qtd       number,
  segundos  number(10,2)
);

prompt 01_tabelas: tabelas ONT_* criadas.
